timer screen test version
Subwan/kek-boy pull request #10
Opened 2024-07-13 11:59 UTC by Lavashic

2024-07-13 13:05 UTC, Subwan requested changes

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/index.tsx
> +  const timerEndedOrTest = timer === TIMER_END || isTest;
Булевые переменные лучше начинать с is/has

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/index.tsx
> +import { DateCounter } from './components/DateCounter';
В components заведи index.ts, чтобы в дальнейшем всё сразу из ./components испортировать

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/index.tsx
> +
Это не понял зачем надо.  У нас два варианта есть, либо таймер, либо нет. Сейчас весь этот прикол с `renderMainScreen` был сделан, только для того, чтобы и там и там одинаковые обёртки были. В твоём случае нужно просто убрать в целом эту функцию и обернуть таймер в `timerScreen`, а  `<Outlet />` и `<EmptyScreen />`  обернуть в `screen` (лучше тоже по типу функции сделать подмену по условию, над посмотреть как их объеденить можн)

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/index.tsx
> +          </div>
Вот это всё тоже лучше вынести в отдельный файл, чтобы не нагромождать текущий логикой отдельной страницы.

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/styles.module.scss
> -  box-shadow:0 0 5vmin 1vmin $black inset;
`box-shadow` потерялся в основной реализации `.screen`

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/styles.module.scss
> +.timerScreen {
Ммм, мне кажется лучше вообще на это забить в целом и растянуть бэкграунд внутри .screen  по height: 100%, width: 100%

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/index.tsx
> +
В стилях смотрю, возможно вообще не нужно это разделение на `screen` и `timerScreen`. Не уверен кстати что при наличии картинки на бэкграунде нужен radial-gradient, но там сам смотри как смотрится (на картинке прост и так вроде градиент есть)

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/styles.module.scss
> +}
Это по идее можно в целом удалить, заменив на паддинг внутри bottomContainer

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/styles.module.scss
> +  margin-bottom: 20px;
там 24px по макетам (если что можно alt зажать и посмотреть расстояния, но без dev мода конечно тяжелее).

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/styles.module.scss
> +  font-size: 36pt;
32px и line-height: 38px

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/styles.module.scss
> +  gap: 60px;
24px

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/index.tsx
> +  number?: number;
не используем ключевые наименования из языка.

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/index.tsx
> +export const DateCounter = (props: DateCounterProps) => {
`export const DateCounter: React.FC<DateCounterProps> = (props) =>`

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/index.tsx
> +}
Поля надо б обязательными сделать

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +.timeNumberContainer {
Мы используем в разработки модули для стилей,  они изолированы от других частей кода, поэтому использовать сложные наменования по типу БЭМ нет нужды, просто называй container и т.д.

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +.middleBlock {
Не используется в данном компоненте

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  gap: 10px
8px

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  background-color: rgba($orange3, 0.1);
#3D2A054D

Там токены цветовые сверху есть, называть этот цвет надо `$darker` (названия выдумки дизайнера, но так потом легче будет ориентироваться).

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  border: 2px solid $orange2;
1px и  цвет `$mainOrange`

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +}
Гит походу сигнализирует, что ты не оставил пустую строку в конце. Претир не работает на стилевые файлы, не правит их...

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  margin-top: 10px;
8px

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  font-size: 24pt;
20px, и `line-height: 24px;`

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  color: white;
используем всё-таки константы цветов - `$white`, на случай если вдруг будет другой белый потом...

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  font-size: 48pt;
32px, и line-height: 38px;

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  height: 70px;
56px на 56px по макетам и ещё добавь `box-sizing: border-box;`, чтобы бордер тоже в этих значениях учитывался.

2024-07-13 13:05 UTC, Subwan commented on src/App/pages/StartPage/styles.module.scss
> +.bottomContainer {
По идее ты можешь сюда бэкграунд имедж засунуть.

2024-07-13 13:05 UTC, Subwan commented on src/img/background_timer.png
эту папку засунь внутрь assets

2024-07-14 00:48 UTC, Lavashic commented on src/App/pages/StartPage/index.tsx
> +          </div>
я ебал, можешь вынести если хочешь, я хуй пойму как тут в реакте чо куда выносится

2024-07-14 00:53 UTC, Lavashic commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  font-size: 48pt;
pt а не px мб? Ну и ещё c line-height всё нахуй вверх уехало а без него было норм, если оно норм выглядит то может нахуй это трогать? нам за это денег не плотют

2024-07-14 00:56 UTC, Lavashic commented on src/App/pages/StartPage/styles.module.scss
> +.bottomContainer {
внатуре

2024-07-14 00:57 UTC, Lavashic commented on src/App/pages/StartPage/index.tsx
> +
ага по второму варику сделал убрал в другой класс так что это верну как было

2024-07-14 11:56 UTC, Subwan requested changes

2024-07-14 11:56 UTC, Subwan commented on src/App/pages/StartPage/components/TimerScreen/index.tsx
> +  minutes?: number;
Эти поля тож обязательные должны быть

2024-07-14 11:56 UTC, Subwan commented on src/App/pages/StartPage/styles.module.scss
> +  background-image: radial-gradient($background4, $background1);
Верни на начальную строчку, чтоб вообще изменений не было.

2024-07-14 11:56 UTC, Subwan commented on src/App/pages/StartPage/index.tsx
> +        <TimerScreen days={timer.days} hours={timer.hours} minutes={timer.minutes} />
`<TimerScreen {...timer} />`

2024-07-14 11:56 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/index.tsx
> +import React from 'react';
И папку эту внеси внутрь TimerScreen, она ток там используется, можно без components

2024-07-14 11:56 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  font-size: 48pt;
Сева ругаться будут, и px у нас в макетах pt почти не используются в целом.

2024-07-14 14:05 UTC, Lavashic commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  font-size: 48pt;
так везде в проекте pt на шрифтах. ну и выглядит хуже. не будет он нихуя ругаться это блять проект КЕК БОЙ

2024-07-14 14:42 UTC, Lavashic commented on src/App/pages/StartPage/index.tsx
> +        <TimerScreen days={timer.days} hours={timer.hours} minutes={timer.minutes} />
![image](https://github.com/user-attachments/assets/10e87a0e-f1d2-45cb-8b9f-cf536983d34d)
хз короче не работает так, похуй, я выходные убивать на то шобы с этим разобраться не хочу, работает и мне достаточно, если тебе за каким-то хуем важны такие мелочи можешь покопаться, мне поебать

2024-07-14 14:43 UTC, Lavashic commented
короч дальше если чо хочешь можешь сам поменять, у меня больше нет особо времени в этом копаться. как по мне - работает и достаточно, я не на работе блять

2024-07-15 17:45 UTC, Subwan commented on src/App/pages/StartPage/components/DateCounter/styles.module.scss
> +  font-size: 48pt;
ну вообще в px если честно в основном

2024-07-15 21:26 UTC, Subwan approved these changes

2024-07-15 21:34 UTC, azhadanov approved these changes

2024-07-15 21:35 UTC, merged