add questionnaire
Subwan/kek-boy pull request #12
Opened 2024-07-13 23:03 UTC by Subwan

2024-07-14 14:09 UTC, Lavashic commented on src/App/pages/StartPage/Questionnaire/components/QuestionBlock/styles.module.scss
> +    display: grid;
добавь user-select: none; я пока тыкал первый вопрос трижды не мог нажать потому что случайно мышкой выделял текст внутри div

2024-07-14 14:09 UTC, Lavashic commented on src/App/pages/StartPage/Questionnaire/components/QuestionBlock/styles.module.scss
> +    display: grid;
можно ваще на весь body это навесить, если ему не надо ничо копипастить в заданиях, а то будет пальцев по экрану если задерживать то случайно выделять текст

2024-07-14 14:30 UTC, Subwan commented on src/App/pages/StartPage/Questionnaire/components/QuestionBlock/styles.module.scss
> +    display: grid;
Исправил

2024-07-14 23:12 UTC, azhadanov requested changes

2024-07-14 23:12 UTC, azhadanov commented on src/App/pages/StartPage/Questionnaire/index.tsx
> +    setCurrentQuestionId((value) => value !== undefined ? value + 1 : 0);
У тебя при таком раскладе последний вопрос никогда не попадет в результирующий массив, передвинь перед  if`ом на 29-ой 35 и 36 строчки.

2024-07-14 23:12 UTC, azhadanov commented on src/App/localStorageApi/questionnaire.ts
> +  calculateResult: () => {
![image](https://github.com/user-attachments/assets/5e3eeee8-4c53-417f-9a1b-ab318e3c9336)
Есть большой шанс, что у тебя неверно считает он
Тут на скрине наиболее частый ответ - 1, а в ответе - 3.
Можешь просто по currentData найти наиболее частый элемент в массиве + прописать дефолтный результат, если у каких-то элементов будет ничья. Вообще без maxAnswered и reduce. 
Только перед этим поправь мой второй коммент, а то у тебя будет 6 элементов вместо семи (на скрине как раз вариант без правки, с массивом из шести элементов)

2024-07-14 23:12 UTC, azhadanov commented on src/App/pages/StartPage/Questionnaire/index.tsx
> +    setCurrentQuestionId((value) => value !== undefined ? value + 1 : 0);
До:
![image](https://github.com/user-attachments/assets/64ccd7bd-d472-4478-b74c-6643cc9a8a67)

2024-07-14 23:12 UTC, azhadanov commented on src/App/pages/StartPage/Questionnaire/index.tsx
> +    setCurrentQuestionId((value) => value !== undefined ? value + 1 : 0);
После:
![image](https://github.com/user-attachments/assets/3e8216af-818f-4d45-9880-68f8a7c6caf4)

2024-07-15 14:10 UTC, Subwan commented on src/App/pages/StartPage/Questionnaire/index.tsx
> +    setCurrentQuestionId((value) => value !== undefined ? value + 1 : 0);
Ага, исправил, правда `setCurrentQuestionId ` двигать не надо по идее, он как раз на 6 позицию массива встанет за вопрос до этого

2024-07-15 14:19 UTC, Subwan commented on src/App/localStorageApi/questionnaire.ts
> +  calculateResult: () => {
Исправил свой вариант.

2024-07-15 14:27 UTC, azhadanov approved these changes

2024-07-15 15:09 UTC, azhadanov approved these changes

2024-07-15 17:34 UTC, merged